# GoReleaser configuration for shortener server
# Usage: goreleaser release --config .goreleaser-server.yaml --clean

version: 2

project_name: shortener

before:
  hooks:
    - go mod tidy
    - go generate ./...

env:
  - CGO_ENABLED=0

builds:
  - id: "shortener-server"
    binary: "shortener-server"
    main: ./main.go
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - loong64
      - riscv64
    ldflags:
      - '-s -w'
      - '-X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}'
    ignore:
      - goos: windows
        goarch: loong64
      - goos: windows
        goarch: riscv64

archives:
  - id: "shortener-server-archive"
    ids: ["shortener-server"]
    name_template: >-
      {{ .ProjectName }}-server-
      {{- .Version }}-
      {{- .Os }}-
      {{- if eq .Arch "x86_64" }}amd64
      {{- else if eq .Arch "aarch64" }}arm64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - LICENSE
      - README.md
      - src: config/config.toml
        dst: config.toml

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  draft: true
  replace_existing_draft: true
  use_existing_draft: true
  replace_existing_artifacts: true
  target_commitish: "{{ .Commit }}"
  make_latest: true
  header: |
    ## {{ .ProjectName }} Server {{ .Version }}
    ---
    Date: {{ .Date }}

  footer: >-

    ---

    Released by [Jetsung Chan](https://github.com/jetsung).

nfpms:
  - id: "shortener-server-package"
    ids: ["shortener-server"]
    bindir: '/opt/{{ .ProjectName }}'
    homepage: 'https://git.jetsung.com/idev/{{ .ProjectName }}'
    maintainer: 'Jetsung Chen <i@jetsung.com>'
    description: |-
      {{ .ProjectName }} Server Service.
    license: Apache 2.0
    formats:
      - deb
      - rpm
    file_name_template: >-
      {{ .ProjectName }}-server_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "x86_64" }}amd64
      {{- else if eq .Arch "aarch64" }}arm64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    contents:
      - src: 'config/config.toml'
        dst: '/opt/{{ .ProjectName }}/config.toml'
        type: config
      - src: 'shortener-server.service'
        dst: '/opt/{{ .ProjectName }}/shortener-server.service'
    scripts:
      preinstall: 'scripts/preinstall.sh'
      postinstall: 'scripts/postinstall.sh'
      preremove: 'scripts/preremove.sh'
      postremove: 'scripts/postremove.sh'