[server]
address = ":8080"
trusted-platform = ""
site_url = "http://localhost:8080"

[api]
url = ""
key = ""

[shortener]
code_length = 6
code_charset = "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"

[database]
type = "sqlite"
log_level = 0

[database.sqlite]
path = "data/shortener.db"

[database.postgres]
host = "postgres"
port = 5432
user = "postgres"
password = "postgres"
database = "shortener"
sslmode = "disable"
timezone = "Asia/Shanghai"

[database.mysql]
host = "mysql"
port = 3306
user = "root"
password = "root"
database = "shortener"
charset = "utf8mb4"
parse_time = true
loc = "Local"

[cache]
enabled = true
type = "redis"
expire = 3600
prefix = "shorten:"

[cache.redis]
host = "redis"
port = 6379
password = ""
db = 0

[cache.valkey]
host = "valkey"
port = 6379
username = ""
password = ""
db = 0
