[server]
address = "127.0.0.1:8080"

trusted-platform = ""

site_url = "http://localhost:8080"

[shortener]
code_length = 6
code_charset = "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"

[database]
type = "sqlite"

[database.sqlite]
path = "data/shortener.db"

[database.postgres]
host = "postgres"
port = 5432
user = "postgres"
password = "postgres"
database = "shortener"
sslmode = "disable"
timezone = "Asia/Shanghai"

[database.mysql]
host = "mysql"
port = 3306
user = "root"
password = "root"
database = "shortener"
charset = "utf8mb4"
parse_time = true
loc = "Local"