services:
  shortener:
    build:
      context: ../../
      dockerfile: deploy/docker/Dockerfile
      args:
        GOPROXY: "https://goproxy.cn"
        OS_MIRROR: "http://mirrors.tencent.com/debian"
    container_name: shortener
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
      - GIN_MODE=release
      - DATABASE_TYPE=mysql
    ports:
      - "8080:8080"
    volumes:
      - ./config.toml:/app/config.toml
    depends_on:
      - mysql
      
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=shortener
