services:
  shortener:
    build:
      context: ../../
      dockerfile: deploy/docker/Dockerfile
      args:
        GOPROXY: "https://goproxy.cn"
        OS_MIRROR: "http://mirrors.tencent.com/debian"
    container_name: shortener
    restart: unless-stopped        
    environment:
      - TZ=Asia/Shanghai
      - GIN_MODE=release
      - DATABASE_TYPE=postgres
    ports:
      - "8080:8080"
    volumes:
      - ./config.toml:/app/config.toml      
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=shortener
