services:
  shortener:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    # image: shortener:local
    container_name: shortener-server
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
      - GIN_MODE=debug
      - DATABASE_TYPE=${DATABASE_TYPE:-sqlite}
    ports:
      - "8080:8080"
    volumes:
      - ./config.toml:/app/config.toml
      - data:/app/data
    profiles:
      - sqlite
      - mysql
      - postgres
      - valkey

  mysql:
    image: mysql:latest
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
      # - MYSQL_USER=root
      # - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=shortener
    profiles:
      - mysql

  postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=shortener
    profiles:
      - postgres

  valkey:
    image: valkey/valkey:latest
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
    profiles:
      - valkey

volumes:
  data:
