[server]
address = "127.0.0.1:8080"

trusted-platform = ""

site_url = "http://localhost:8080"

[shortener]
code_length = 6
code_charset = "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"

[database]
type = "sqlite"

[database.sqlite]
path = "data/shortener.db"