name: Docker-Main

on:
  push:
    branches:
      - main
    paths:
      - docker-bake.hcl
      - "deploy/docker/Dockerfile"
      - ".github/workflows/docker-main.yml"
      - "internal/**"
      - "go.mod"
      - "go.sum"
      - "justfile"

env:
  branch: main
  image_org: idevsig
  package_name: shortener-server
  acr_registry: registry.cn-guangzhou.aliyuncs.com
  hcr_registry: swr.ap-southeast-3.myhuaweicloud.com
  tcr_registry: ccr.ccs.tencentyun.com

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry (ghcr.io)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        env:
          IMAGE_REPO: ghcr.io/${{ github.repository_owner }}/${{ env.package_name }}
        with:
          images: |
            ${{ env.IMAGE_REPO || '' }}
          labels: |
            org.opencontainers.image.title=Shortener
            org.opencontainers.image.description=Shortener is a URL shortening service.
            org.opencontainers.image.vendor=Jetsung Chan
          tags: |
            ${{ env.branch }}

      - name: Build
        uses: docker/bake-action@v6
        with:
          files: |
            ./docker-bake.hcl
            cwd://${{ steps.meta.outputs.bake-file }}
          targets: release
          push: ${{ github.event_name != 'pull_request' }}

      - uses: actions/delete-package-versions@v5
        continue-on-error: true
        with:
          package-name: ${{ env.package_name }}
          package-type: 'container'
          min-versions-to-keep: 2
          delete-only-untagged-versions: 'true'

  sync-to-dockerhub:
    needs: build
    runs-on: ubuntu-24.04
    steps:
    - name: Install Dependencies
      run: |
        apt-get update
        apt-get install -y skopeo
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Sync to DockerHub
      env:
        SRC_IMAGE: ghcr.io/${{ github.repository_owner }}/${{ env.package_name }}:${{ env.branch }}
        DEST_IMAGE: ${{ env.image_org }}/${{ env.package_name }}:${{ env.branch }}
      run: |
        if ! docker info > /dev/null 2>&1; then
          echo "docker.io Docker login failed!"
          exit 1
        fi
        echo "Syncing to DockerHub..."
        skopeo copy --all \
          docker://${{ env.SRC_IMAGE }} \
          docker://${{ env.DEST_IMAGE }}

  sync-to-aliyun:
    needs: build
    runs-on: ubuntu-24.04
    steps:
    - name: Install Dependencies
      run: |
        apt-get update
        apt-get install -y skopeo
    - name: Login to Aliyun
      uses: docker/login-action@v3
      with:
        registry: ${{ env.acr_registry }}
        username: ${{ secrets.ALIYUN_USERNAME }}
        password: ${{ secrets.ALIYUN_TOKEN }}
    - name: Sync to Aliyun
      env:
        SRC_IMAGE: ghcr.io/${{ github.repository_owner }}/${{ env.package_name }}:${{ env.branch }}
        DEST_IMAGE: ${{ env.acr_registry }}/${{ env.image_org }}/${{ env.package_name }}:${{ env.branch }}
      run: |
        if ! docker info > /dev/null 2>&1; then
          echo "Aliyun Docker login failed!"
          exit 1
        fi
        echo "Syncing to Aliyun..."
        skopeo copy --all \
          docker://${{ env.SRC_IMAGE }} \
          docker://${{ env.DEST_IMAGE }}

  sync-to-tencent:
    needs: build
    runs-on: ubuntu-24.04
    steps:
    - name: Install Dependencies
      run: |
        apt-get update
        apt-get install -y skopeo
    - name: Login to Tencent
      uses: docker/login-action@v3
      with:
        registry: ${{ env.tcr_registry }}
        username: ${{ secrets.TENCENT_USERNAME }}
        password: ${{ secrets.TENCENT_TOKEN }}
    - name: Sync to Tencent
      env:
        SRC_IMAGE: ghcr.io/${{ github.repository_owner }}/${{ env.package_name }}:${{ env.branch }}
        DEST_IMAGE: ${{ env.tcr_registry }}/${{ env.image_org }}/${{ env.package_name }}:${{ env.branch }}
      run: |
        if ! docker info > /dev/null 2>&1; then
          echo "Tencent Docker login failed!"
          exit 1
        fi
        echo "Syncing to Tencent..."
        skopeo copy --all \
          docker://${{ env.SRC_IMAGE }} \
          docker://${{ env.DEST_IMAGE }}
