name: Docker-Release

on:
  push:
    tags:
      - "*"

env:
  branch: latest
  image_org: idevsig
  package_name: shortener-server
  acr_registry: registry.cn-guangzhou.aliyuncs.com
  hcr_registry: swr.ap-southeast-3.myhuaweicloud.com
  tcr_registry: ccr.ccs.tencentyun.com

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.set_tag.outputs.tag }}
      repo: ${{ steps.set_repo.outputs.repo }}
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set tag without 'v' prefix
        id: set_tag
        run: |
            ref_tag="${{ github.ref_name }}"
            ref_tag="${ref_tag#v}"
            echo "Detected tag: $ref_tag"
            echo "tag=$ref_tag" >> $GITHUB_ENV
            echo "tag=$ref_tag" >> $GITHUB_OUTPUT
      - name: Set repo
        id: set_repo
        run: |
          IMAGE_REPO="${{ env.image_org }}/${{ env.package_name }}"
          echo "repo=${{ env.IMAGE_REPO }}" >> $GITHUB_OUTPUT
          echo "repo=${{ env.IMAGE_REPO }}" >> $GITHUB_ENV

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.repo || '' }}
          labels: |
            org.opencontainers.image.title=Shortener
            org.opencontainers.image.description=Shortener is a URL shortening service.
            org.opencontainers.image.vendor=Jetsung Chan
          tags: |
            ${{ env.tag }}
            latest

      - name: Build with Bake
        uses: docker/bake-action@v6
        with:
          files: |
            ./docker-bake.hcl
            cwd://${{ steps.meta.outputs.bake-file }}
          targets: release
          push: ${{ github.event_name != 'pull_request' }}

  sync-to-ghcr:
    needs: build
    runs-on: ubuntu-24.04
    steps:
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y skopeo
        skopeo --version
    - name: Login to GitHub Container Registry (ghcr.io)
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Sync to GitHub Container Registry (ghcr.io)
      env:
        SRC_IMAGE: ${{ needs.build.outputs.repo }}:latest
        DEST_REPO: ghcr.io/${{ github.repository_owner }}/${{ env.package_name }}
        DEST_TAG: ${{ needs.build.outputs.tag }}
      run: |
        skopeo copy --all docker://${{ env.SRC_IMAGE }} docker://${{ env.DEST_REPO }}:${{ env.DEST_TAG }}
        skopeo copy --all docker://${{ env.SRC_IMAGE }} docker://${{ env.DEST_REPO }}:latest
    - uses: actions/delete-package-versions@v5
      continue-on-error: true
      with:
        package-name: ${{ env.package_name }}
        package-type: 'container'
        min-versions-to-keep: 2
        delete-only-untagged-versions: 'true'

  sync-to-aliyun:
    needs: build
    runs-on: ubuntu-24.04
    steps:
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y skopeo
    - name: Login to Aliyun
      uses: docker/login-action@v3
      with:
        registry: ${{ env.acr_registry }}
        username: ${{ secrets.ALIYUN_USERNAME }}
        password: ${{ secrets.ALIYUN_TOKEN }}
    - name: Sync to Aliyun
      env:
        SRC_IMAGE: ${{ needs.build.outputs.repo }}:latest
        DEST_REPO: ${{ env.acr_registry }}/${{ env.image_org }}/${{ env.package_name }}
        DEST_TAG: ${{ needs.build.outputs.tag }}
      run: |
        skopeo copy --all docker://${{ env.SRC_IMAGE }} docker://${{ env.DEST_REPO }}:${{ env.DEST_TAG }}
        skopeo copy --all docker://${{ env.SRC_IMAGE }} docker://${{ env.DEST_REPO }}:latest

  sync-to-tencent:
    needs: build
    runs-on: ubuntu-24.04
    steps:
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y skopeo
    - name: Login to Tencent
      uses: docker/login-action@v3
      with:
        registry: ${{ env.tcr_registry }}
        username: ${{ secrets.TENCENT_USERNAME }}
        password: ${{ secrets.TENCENT_TOKEN }}
    - name: Sync to  Tencent
      env:
        SRC_IMAGE: ${{ needs.build.outputs.repo }}:latest
        DEST_REPO: ${{ env.tcr_registry }}/${{ env.image_org }}/${{ env.package_name }}
        DEST_TAG: ${{ needs.build.outputs.tag }}
      run: |
        skopeo copy --all docker://${{ env.SRC_IMAGE }} docker://${{ env.DEST_REPO }}:${{ env.DEST_TAG }}
        skopeo copy --all docker://${{ env.SRC_IMAGE }} docker://${{ env.DEST_REPO }}:latest
